// GM SoundFont bank map over the raw int16 blob in sounds/gm/fonts.bin.
// Bank + map taken from Leeman1982/gm2350 (sf2_to_amy.py bake of
// GeneralUser GS et al., 160 presets, 22.05kHz mono). The blob is
// provided at runtime via gm_pcm (mmapped from the `fonts` flash
// partition on ESP32-S3). Only used when GM_FONTS is defined.
// GM program/drum-note -> preset index tables live in amy/gm.py.
//
// Regenerated by tools/gm/rebake_gm.py (see tools/gm/README.md).
// The original bake applied a hard duration cap (22747 frames for looped
// samples, 19247 for one-shots) and dropped the sustain loop whenever the
// cap bound. This rebake restores the real length and the SoundFont loop
// for the melodic presets that were damaged, and copies every other preset
// byte-for-byte from the previous blob.
#ifndef __PCM_GM_H
#define __PCM_GM_H
#define GM_PRESET_BASE 512
#define GM_NUM_SAMPLES 160
#define GM_SAMPLE_RATE 22050
#define GM_BIN_FRAMES 1808935
const pcm_map_t gm_map[GM_NUM_SAMPLES] PROGMEM = {
    /* [0] preset 512 */ {0, 44474, 21957, 44473, 60}, /* Grand Piano-C4 */
    /* [1] preset 513 */ {44474, 19082, 18958, 19042, 60}, /* CP-80 EP-C4 */
    /* [2] preset 514 */ {63556, 3442, 3326, 3438, 55}, /* Rhodes-G2 P */
    /* [3] preset 515 */ {66998, 8240, 4492, 7138, 60}, /* DX7 Wave */
    /* [4] preset 516 */ {75238, 13961, 13802, 13928, 65}, /* Harpsi_1-F4 */
    /* [5] preset 517 */ {89199, 12709, 12577, 12679, 57}, /* Clavinet-A3 */
    /* [6] preset 518 */ {101908, 5422, 5275, 5417, 63}, /* Celeste-D#4 */
    /* [7] preset 519 */ {107330, 25226, 21478, 24124, 80}, /* Glockenspiel-G#4 */
    /* [8] preset 520 */ {132556, 5669, 5054, 5646, 62}, /* Vibraphone-D4 */
    /* [9] preset 521 */ {138225, 17464, 17230, 17400, 60}, /* Marimba-C4 */
    /* [10] preset 522 */ {155689, 8569, 0, 8569, 76}, /* Xylophone-E4 */
    /* [11] preset 523 */ {164258, 35193, 23695, 35189, 72}, /* Tubular Bells-C4 */
    /* [12] preset 524 */ {199451, 22626, 22566, 22622, 67}, /* Dulcimer-C#4 */
    /* [13] preset 525 */ {222077, 1558, 1274, 1528, 53}, /* Hammond Organ-5 */
    /* [14] preset 526 */ {223635, 2688, 124, 2684, 89}, /* Organ Slow-D#3 */
    /* [15] preset 527 */ {226323, 1910, 306, 1906, 72}, /* Organ Fast-C3 */
    /* [16] preset 528 */ {228233, 8914, 5166, 7812, 58}, /* Pipe Organ-G#2 */
    /* [17] preset 529 */ {237147, 6924, 6846, 6920, 62}, /* Accordion-A#2 */
    /* [18] preset 530 */ {244071, 5108, 5010, 5104, 58}, /* Accordion-F#2 */
    /* [19] preset 531 */ {249179, 3709, 3545, 3678, 64}, /* Harmonica-E3 */
    /* [20] preset 532 */ {252888, 8413, 8304, 8388, 72}, /* Nylon Guitar-C4 */
    /* [21] preset 533 */ {261301, 18043, 14295, 16941, 59}, /* Steel Guitar-B4 */
    /* [22] preset 534 */ {279344, 7721, 7607, 7691, 60}, /* Jazz Guitar-C4 */
    /* [23] preset 535 */ {287065, 26299, 24934, 26270, 59}, /* Clean Guitar-B3 */
    /* [24] preset 536 */ {313364, 3101, 2358, 2428, 63}, /* Muted Guitar-D#4 */
    /* [25] preset 537 */ {316465, 15360, 14375, 15136, 60}, /* Overdrive Guitar-C4 */
    /* [26] preset 538 */ {331825, 25264, 25055, 25144, 59}, /* Distortion Gt-B3 */
    /* [27] preset 539 */ {357089, 2938, 2723, 2934, 67}, /* Gtr Harmonics-B2 */
    /* [28] preset 540 */ {360027, 4630, 4529, 4597, 64}, /* Acoustic Bass-G#3 */
    /* [29] preset 541 */ {364657, 5130, 5074, 5126, 69}, /* Finger Bass-G1 */
    /* [30] preset 542 */ {369787, 8990, 8874, 8976, 57}, /* Pick Bass-G1 */
    /* [31] preset 543 */ {378777, 11611, 11465, 11571, 56}, /* Fretless Bass-G#4 */
    /* [32] preset 544 */ {390388, 3038, 2426, 3027, 57}, /* Slap Bass 1-A4 */
    /* [33] preset 545 */ {393426, 8429, 8172, 8424, 41}, /* Slap Bass 2-F3F */
    /* [34] preset 546 */ {401855, 205, 101, 201, 57}, /* Wave_Pulse3750-057 */
    /* [35] preset 547 */ {402060, 6678, 6233, 6662, 51}, /* Synth Bass 2-F2 */
    /* [36] preset 548 */ {408738, 32087, 19411, 32085, 59}, /* Violin-B3 */
    /* [37] preset 549 */ {440825, 21446, 17698, 20344, 60}, /* Viola-60 */
    /* [38] preset 550 */ {462271, 26527, 22779, 25425, 59}, /* Cello-B2 */
    /* [39] preset 551 */ {488798, 19750, 16002, 18648, 64}, /* Cello-E3 */
    /* [40] preset 552 */ {508548, 50188, 11915, 50184, 57}, /* StrLoop - A2 */
    /* [41] preset 553 */ {558736, 14634, 0, 14634, 56}, /* Pizz. Strings-G#3 */
    /* [42] preset 554 */ {573370, 15463, 13239, 15430, 60}, /* Orchestral Harp-C4 */
    /* [43] preset 555 */ {588833, 51286, 39836, 51240, 50}, /* Timpani Soft */
    /* [44] preset 556 */ {640119, 39044, 13023, 39042, 60}, /* StrLoop - C3 */
    /* [45] preset 557 */ {679163, 5554, 1806, 4452, 60}, /* Synth Strings 1-C4 */
    /* [46] preset 558 */ {684717, 3750, 2, 2648, 69}, /* Synth Strings 2-C3 */
    /* [47] preset 559 */ {688467, 15672, 11924, 14570, 59}, /* Concert Choir-B3 */
    /* [48] preset 560 */ {704139, 5761, 2367, 5757, 69}, /* Voice Oohs-B2 */
    /* [49] preset 561 */ {709900, 14639, 10891, 13537, 61}, /* Synth Vox Aahs-C#4 */
    /* [50] preset 562 */ {724539, 9649, 0, 9649, 76}, /* Orchestra Hit-1 */
    /* [51] preset 563 */ {734188, 7771, 7627, 7722, 58}, /* Trumpet-A#3 */
    /* [52] preset 564 */ {741959, 4412, 4333, 4408, 62}, /* Trombone-D3 */
    /* [53] preset 565 */ {746371, 6450, 6256, 6445, 46}, /* Tuba-A#1 */
    /* [54] preset 566 */ {752821, 10258, 8364, 10235, 62}, /* Muted Trumpet-D4 */
    /* [55] preset 567 */ {763079, 13026, 9278, 11924, 63}, /* French Horn-D#3 */
    /* [56] preset 568 */ {776105, 50216, 13012, 50212, 60}, /* Brass Section-C4 */
    /* [57] preset 569 */ {826321, 255, 150, 251, 57}, /* Wave_Saw-057 */
    /* [58] preset 570 */ {826576, 8531, 5880, 8527, 73}, /* Soprano Sax-C2 */
    /* [59] preset 571 */ {835107, 11026, 7278, 9924, 62}, /* Alto Sax-D4 */
    /* [60] preset 572 */ {846133, 3449, 3370, 3445, 62}, /* Tenor Sax-D3 */
    /* [61] preset 573 */ {849582, 5392, 5205, 5264, 66}, /* Baritone Sax-A#2 */
    /* [62] preset 574 */ {854974, 25887, 22139, 24785, 61}, /* Oboe-C#3 */
    /* [63] preset 575 */ {880861, 15714, 11966, 14612, 61}, /* English Horn-C#3 */
    /* [64] preset 576 */ {896575, 3972, 3862, 3948, 60}, /* Bassoon-C4 */
    /* [65] preset 577 */ {900547, 5623, 3337, 5581, 58}, /* Clarinet-A#3 */
    /* [66] preset 578 */ {906170, 15295, 11547, 14193, 82}, /* Piccolo-A#1 */
    /* [67] preset 579 */ {921465, 15753, 12005, 14651, 61}, /* Flute-C#4 */
    /* [68] preset 580 */ {937218, 16905, 13157, 15803, 62}, /* Recorder-D3 */
    /* [69] preset 581 */ {954123, 17500, 13752, 16398, 81}, /* Pan Flute_2 */
    /* [70] preset 582 */ {971623, 31616, 17782, 31557, 54}, /* Bottle Blow */
    /* [71] preset 583 */ {1003239, 32839, 21269, 32335, 72}, /* Shakuhachi */
    /* [72] preset 584 */ {1036078, 118, 29, 88, 66}, /* Sine-375Hz */
    /* [73] preset 585 */ {1036196, 22747, 0, 22747, 73}, /* Ocarina-C#5 */
    /* [74] preset 586 */ {1058943, 255, 150, 251, 57}, /* Wave_Pulse5000-057 */
    /* [75] preset 587 */ {1059198, 11361, 7613, 10259, 62}, /* Chiff Flute */
    /* [76] preset 588 */ {1070559, 3692, 14, 3657, 60}, /* Solo Vox-C4 */
    /* [77] preset 589 */ {1074251, 6280, 2532, 5178, 60}, /* Stacked Saw-C4 */
    /* [78] preset 590 */ {1080531, 255, 150, 251, 57}, /* Wave_Ramp-057 */
    /* [79] preset 591 */ {1080786, 4492, 744, 3390, 84}, /* Stacked Saw-C6 */
    /* [80] preset 592 */ {1085278, 4025, 277, 2923, 64}, /* Synth Bell-1a */
    /* [81] preset 593 */ {1089303, 3779, 31, 2677, 72}, /* Synth Vox Oohs-C3 */
    /* [82] preset 594 */ {1093082, 44309, 0, 44309, 55}, /* Sitar-G3 */
    /* [83] preset 595 */ {1137391, 3093, 3004, 3064, 66}, /* Banjo-F4 */
    /* [84] preset 596 */ {1140484, 614, 551, 598, 70}, /* Shamisen-C3 */
    /* [85] preset 597 */ {1141098, 23435, 23198, 23398, 57}, /* Koto-A3 */
    /* [86] preset 598 */ {1164533, 4695, 4638, 4691, 68}, /* Kalimba-C3 */
    /* [87] preset 599 */ {1169228, 928, 902, 926, 94}, /* ChanterAx1 */
    /* [88] preset 600 */ {1170156, 311, 260, 307, 70}, /* Shenai-C3 */
    /* [89] preset 601 */ {1170467, 5032, 4432, 5028, 102}, /* Carillon-C6 */
    /* [90] preset 602 */ {1175499, 2515, 0, 2515, 72}, /* Agogo */
    /* [91] preset 603 */ {1178014, 19197, 19066, 19151, 60}, /* Steel Drums-C4 */
    /* [92] preset 604 */ {1197211, 713, 0, 713, 60}, /* Wood Block Med */
    /* [93] preset 605 */ {1197924, 11853, 9471, 11845, 60}, /* Taiko Drum */
    /* [94] preset 606 */ {1209777, 22747, 0, 22747, 60}, /* Standard Tom 3 */
    /* [95] preset 607 */ {1232524, 5950, 0, 5950, 60}, /* Electric Tom */
    /* [96] preset 608 */ {1238474, 19247, 0, 19247, 60}, /* Reverse Cymbal */
    /* [97] preset 609 */ {1257721, 3088, 0, 3088, 69}, /* Fret Slide */
    /* [98] preset 610 */ {1260809, 4635, 0, 4635, 61}, /* Breath Noise-1 */
    /* [99] preset 611 */ {1265444, 3750, 2, 2648, 60}, /* Seashore */
    /* [100] preset 612 */ {1269194, 22747, 0, 22747, 60}, /* Birds */
    /* [101] preset 613 */ {1291941, 792, 4, 790, 60}, /* LeFone */
    /* [102] preset 614 */ {1292733, 3750, 2, 2648, 60}, /* Helicopter */
    /* [103] preset 615 */ {1296483, 78937, 48942, 78936, 60}, /* Applause */
    /* [104] preset 616 */ {1375420, 4134, 0, 4134, 60}, /* Gun Shot */
    /* [105] preset 617 */ {1379554, 715, 0, 715, 45}, /* Filter Snap */
    /* [106] preset 618 */ {1380269, 2320, 0, 2320, 40}, /* Slap */
    /* [107] preset 619 */ {1382589, 3112, 0, 3112, 29}, /* Scratch Push */
    /* [108] preset 620 */ {1385701, 4029, 0, 4029, 30}, /* Scratch Pull */
    /* [109] preset 621 */ {1389730, 3542, 0, 3542, 31}, /* Sticks */
    /* [110] preset 622 */ {1393272, 51, 0, 51, 60}, /* Square Click */
    /* [111] preset 623 */ {1393323, 318, 0, 318, 44}, /* TR-808 Click */
    /* [112] preset 624 */ {1393641, 318, 0, 318, 45}, /* TR-808 Click */
    /* [113] preset 625 */ {1393959, 3183, 0, 3183, 35}, /* Standard Kick 2 */
    /* [114] preset 626 */ {1397142, 2494, 0, 2494, 36}, /* Standard Kick 3 */
    /* [115] preset 627 */ {1399636, 2286, 0, 2286, 37}, /* Jazz Rim Shot */
    /* [116] preset 628 */ {1401922, 11982, 0, 11982, 60}, /* Standard Snare 1_v1 */
    /* [117] preset 629 */ {1413904, 1802, 0, 1802, 54}, /* Hand Clap */
    /* [118] preset 630 */ {1415706, 10064, 0, 10064, 38}, /* Standard Snare 3 */
    /* [119] preset 631 */ {1425770, 22747, 0, 22747, 42}, /* Standard Tom 5 */
    /* [120] preset 632 */ {1448517, 3594, 0, 3594, 42}, /* Hi-Hat Closed Hard */
    /* [121] preset 633 */ {1452111, 1874, 0, 1874, 53}, /* Hi-Hat Pedal */
    /* [122] preset 634 */ {1453985, 22747, 0, 22747, 45}, /* Standard Tom 4 */
    /* [123] preset 635 */ {1476732, 22747, 0, 22747, 46}, /* Hi-Hat Open */
    /* [124] preset 636 */ {1499479, 22747, 0, 22747, 47}, /* Standard Tom 3 */
    /* [125] preset 637 */ {1522226, 20374, 19148, 19946, 48}, /* Standard Tom 2 */
    /* [126] preset 638 */ {1542600, 19247, 0, 19247, 49}, /* Crash Cymbal */
    /* [127] preset 639 */ {1561847, 16339, 15587, 15999, 50}, /* Standard Tom 1 */
    /* [128] preset 640 */ {1578186, 19247, 0, 19247, 51}, /* Ride Cymbal */
    /* [129] preset 641 */ {1597433, 22159, 18712, 22155, 58}, /* Chinese Cymbal */
    /* [130] preset 642 */ {1619592, 19247, 0, 19247, 53}, /* Ride Bell */
    /* [131] preset 643 */ {1638839, 3350, 931, 3346, 66}, /* Tambourine */
    /* [132] preset 644 */ {1642189, 19247, 0, 19247, 55}, /* Splash Cymbal */
    /* [133] preset 645 */ {1661436, 1917, 0, 1917, 61}, /* Cowbell */
    /* [134] preset 646 */ {1663353, 19247, 0, 19247, 57}, /* Crash Cymbal */
    /* [135] preset 647 */ {1682600, 19247, 0, 19247, 58}, /* Vibra Slap */
    /* [136] preset 648 */ {1701847, 952, 0, 952, 74}, /* Bongo Rim */
    /* [137] preset 649 */ {1702799, 1156, 0, 1156, 73}, /* Bongo Tone */
    /* [138] preset 650 */ {1703955, 1193, 0, 1193, 67}, /* Conga High Muted */
    /* [139] preset 651 */ {1705148, 3921, 0, 3921, 63}, /* Conga High Open */
    /* [140] preset 652 */ {1709069, 1904, 0, 1904, 69}, /* Tumba Low */
    /* [141] preset 653 */ {1710973, 4621, 0, 4621, 70}, /* Timbale Rim */
    /* [142] preset 654 */ {1715594, 5861, 0, 5861, 66}, /* Timbale Low */
    /* [143] preset 655 */ {1721455, 1426, 0, 1426, 70}, /* Cabasa */
    /* [144] preset 656 */ {1722881, 3345, 0, 3345, 69}, /* Maracas */
    /* [145] preset 657 */ {1726226, 1609, 0, 1609, 71}, /* Whistle Short */
    /* [146] preset 658 */ {1727835, 6621, 0, 6621, 72}, /* Whistle Long */
    /* [147] preset 659 */ {1734456, 784, 0, 784, 73}, /* Guiro Short */
    /* [148] preset 660 */ {1735240, 5178, 0, 5178, 74}, /* Guiro Long */
    /* [149] preset 661 */ {1740418, 932, 0, 932, 75}, /* Claves */
    /* [150] preset 662 */ {1741350, 3617, 0, 3617, 78}, /* Cuica Mute */
    /* [151] preset 663 */ {1744967, 5031, 0, 5031, 79}, /* Cuica Open */
    /* [152] preset 664 */ {1749998, 1034, 166, 1030, 93}, /* Triangle (Perc) */
    /* [153] preset 665 */ {1751032, 1034, 166, 1030, 94}, /* Triangle (Perc) */
    /* [154] preset 666 */ {1752066, 2813, 0, 2813, 82}, /* Shaker */
    /* [155] preset 667 */ {1754879, 7697, 0, 7697, 83}, /* Jingle Bell */
    /* [156] preset 668 */ {1762576, 22747, 0, 22747, 84}, /* Chimes */
    /* [157] preset 669 */ {1785323, 652, 0, 652, 85}, /* Castanets */
    /* [158] preset 670 */ {1785975, 3713, 0, 3713, 86}, /* Surdo Muted */
    /* [159] preset 671 */ {1789688, 19247, 0, 19247, 87}, /* Surdo Open */
};
#endif // __PCM_GM_H
